# Generated by Django 4.0.4 on 2022-05-19 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_user_date_session_user_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_date',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='session',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
