# Generated by Django 4.0.4 on 2022-05-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_user_date_session_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_user',
            field=models.CharField(default='google@gmail.com', max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=32),
        ),
    ]
