# Generated by Django 4.0.4 on 2022-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_email_user_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_user',
            field=models.EmailField(default='google@gmail.com', max_length=140),
        ),
    ]
